### PR TITLE
My homework about git (week1) - create and commit 3 files

### PR DESCRIPTION
**Pull request by olhasashchuk**
I created, added and committed 3 files about counties, which I have been; my favorite food recipe; and my second favorite food recipe.

### CODE REVIEW

**Review by jason-vasilev — COMMENTED** [review]
Well done, Olha. I'm glad you have also filled in a detailed PR description, besides good commit messages. Could you add one more country to the file with countries and check how it's reflected in the PR? I will approve immediately after that.

**Comment by olhasashchuk** [comment]
Jason, hello! Thanks! I'm doing it now.

**Review by jason-vasilev — APPROVED** [review]
Perfect. You can merge it now - I will update the status in the homework sheet to approved.

**Comment by olhasashchuk** [comment]
Thank you so much!

**Pull request merged**
